export type Action = {
    type: string,
    payload?: any,
}

export const IS_CONNECTION = "IS_CONNECTION";
export const HANDLE_LOADING_PROGRESS = "HANDLE_LOADING_PROGRESS";
export const HANDLE_NETWORK = "HANDLE_NETWORK";
export const IS_NETWORK_CHANGED = "IS_NETWORK_CHANGED";

export const HANDLE_WALLET_NAME = "HANDLE_WALLET_NAME";
export const HANDLE_WALLET_ADDRESS = "HANDLE_WALLET_ADDRESS";

export const LOAD_DELEGATION_LIST = "LOAD_DELEGATION_LIST";
export const LOAD_VALIDATOR_LIST = "LOAD_VALIDATOR_LIST";
export const UPDATE_DELEGATE_STATE = "UPDATE_DELEGATE_STATE";
export const UPDATE_VALIDATOR_STATE = "UPDATE_VALIDATOR_STATE";
export const UPDATE_STAKING_REWARD = "UPDATE_STAKING_REWARD";