export type Action = {
    type: string,
    payload?: any,
}
export const CURRENT_APP_VERSION = "CURRENT_APP_VERSION";
export const CHAIN_VERSION = "CHAIN_VERSION";
export const SDK_VERSION = "SDK_VERSION";

export const LOCK_STATION = "LOCK_STATION";
export const APP_STATE = "APP_STATE";
export const APP_PAUSED_TIME = "APP_PAUSED_TIME";
export const LOGGEDIN = "LOGGEDIN";
export const IS_BIOAUTH_IN_PROGRESS = "IS_BIOAUTH_IN_PROGRESS";

export const IS_CONNECTION = "IS_CONNECTION";
export const HANDLE_LOADING_PROGRESS = "HANDLE_LOADING_PROGRESS";
export const HANDLE_NETWORK = "HANDLE_NETWORK";
export const IS_NETWORK_CHANGED = "IS_NETWORK_CHANGED";

export const DATA_LOAD_STATUS = "DATA_LOAD_STATUS";

export const HANDLE_WALLET_NAME = "HANDLE_WALLET_NAME";
export const HANDLE_WALLET_ADDRESS = "HANDLE_WALLET_ADDRESS";
export const HANDLE_DST_ADDRESS = "HANDLE_DST_ADDRESS";

export const HANDLE_CURRENCY = "HANDLE_CURRENCY";

export const UPDATE_DELEGATE_STATE = "UPDATE_DELEGATE_STATE";
export const UPDATE_VALIDATOR_STATE = "UPDATE_VALIDATOR_STATE";
export const UPDATE_STAKING_REWARD = "UPDATE_STAKING_REWARD";

export const HANDLE_SCROLL_TO_TOP = "HANDLE_SCROLL_TO_TOP";
export const HANDLE_NETWORK_CHANGE_ACTIVATE = "HANDLE_NETWORK_CHANGE_ACTIVATE";

export const HOME_QR_SCANNER_MODAL = "HOME_QR_SCANNER_MODAL";
export const WALLET_CONNECT_LOGIN_MODAL = "WALLET_CONNECT_LOGIN_MODAL";
export const WALLET_RESULT_MODAL = "WALLET_RESULT_MODAL";