require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'firma_station_mobile' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  target 'firma_station_mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  
    Dir.glob("Pods/**/hash.hpp").each do |file_path|
      text = File.read(file_path)
      updated_text = text.gsub("std::unary_function", "std::__unary_function")
      
      if text != updated_text # Save if changed
        File.write(file_path, updated_text)
        puts "Modified std::unary_function to std::__unary_function in #{file_path}"
      else
        puts "No changes needed in #{file_path}"
      end
    end
  end
end