# Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip
# Upper lines are disabled: For react-native-permissions
def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

# Disable VisionCamera CLLocation APIs to avoid iOS location privacy requirement.
$VCEnableLocation = false

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Add react-native-permissions
# ⬇️ uncomment the permissions you need
setup_permissions(['Camera','FaceID'])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'firma_station_mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # Force set iOS target to min version.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
      end
    end
    # Build only for the active arch. This line added to exclude armv7.
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #       config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    #   end
    # end
    # installer.pods_project.targets.each do |t|
    #   t.build_configurations.each do |config|
    #     config.build_settings['NODE_BINARY'] = ENV['NODE_BINARY'] || `which node`.strip
    #   end
    # end
  end
end
